#Requires -Version 7
<#
.SYNOPSIS
    Fetch Microsoft Intune (MEM) network service endpoints and emit an
    as-code firewall allow-list.

.DESCRIPTION
    Pulls the authoritative endpoint set from the Microsoft 365 IP/URL web
    service (endpoints.office.com, ServiceArea=MEM) — the same source
    Microsoft updates monthly — and generates:

      intune-network-endpoints.md   human-readable allow-list (URLs/IPs/ports)
      intune-allowlist-ipv4.txt     flat IPv4 CIDR list for a router ipset/nftables set
      intune-allowlist-ipv6.txt     flat IPv6 CIDR list

    Egress in this lab is enforced at the OpenWrt router (see
    docs/network-zones.md). The management zone (AsharPC) already permits
    outbound 443/80 to these — this artifact documents/pins that surface and
    future-proofs a tighter egress policy. Windows Defender Firewall on the
    endpoint is left at its default (allow outbound); FQDN-based allow rules
    aren't a native Windows Firewall capability, so host-level control, if
    ever needed, uses the IPv4/IPv6 CIDR lists.

.NOTES
    Microsoft refreshes these endpoints ~monthly. Re-run and re-commit to
    keep the allow-list current. Diff the change note (endpoints.office.com
    /version) before applying to the router.

.EXAMPLE
    ./get-intune-endpoints.ps1
#>
param(
    [string] $OutputDir = $PSScriptRoot,
    [ValidateSet('Worldwide','USGovGCCHigh','USGovDoD','China')]
    [string] $Instance = 'Worldwide'
)

$ErrorActionPreference = 'Stop'
$clientId = (New-Guid).Guid
$base = "https://endpoints.office.com/endpoints/$Instance"
$uri  = "${base}?ServiceAreas=MEM&clientrequestid=$clientId"

Write-Host "Fetching Intune (MEM) endpoints from Microsoft ($Instance)..." -ForegroundColor Cyan
$data = Invoke-RestMethod -Uri $uri -Method GET

# Current published version (change-tracking)
$ver = (Invoke-RestMethod -Uri "https://endpoints.office.com/version/$Instance`?clientrequestid=$clientId").latest

$reqUrls = [System.Collections.Generic.SortedSet[string]]::new()
$optUrls = [System.Collections.Generic.SortedSet[string]]::new()
$ipv4    = [System.Collections.Generic.SortedSet[string]]::new()
$ipv6    = [System.Collections.Generic.SortedSet[string]]::new()
$tcp     = [System.Collections.Generic.SortedSet[string]]::new()
$udp     = [System.Collections.Generic.SortedSet[string]]::new()

foreach ($e in $data) {
    $required = [bool]$e.required
    foreach ($u in $e.urls)  { if ($required) { [void]$reqUrls.Add($u) } else { [void]$optUrls.Add($u) } }
    foreach ($ip in $e.ips)  { if ($ip -match ':') { [void]$ipv6.Add($ip) } else { [void]$ipv4.Add($ip) } }
    if ($e.tcpPorts) { foreach ($p in ($e.tcpPorts -split ',')) { [void]$tcp.Add($p.Trim()) } }
    if ($e.udpPorts) { foreach ($p in ($e.udpPorts -split ',')) { [void]$udp.Add($p.Trim()) } }
}
# Optional URLs already covered by a required entry are noise; drop exact dups
$optOnly = $optUrls | Where-Object { -not $reqUrls.Contains($_) }

$stamp = (Get-Date).ToString('yyyy-MM-dd')

# --- flat CIDR lists (router ipset / nftables) ---
$ipv4 | Set-Content "$OutputDir/intune-allowlist-ipv4.txt" -Encoding ascii
$ipv6 | Set-Content "$OutputDir/intune-allowlist-ipv6.txt" -Encoding ascii

# --- markdown allow-list ---
$md = [System.Text.StringBuilder]::new()
[void]$md.AppendLine("# Intune network service endpoints (allow-list)")
[void]$md.AppendLine('')
[void]$md.AppendLine("> Generated by ``get-intune-endpoints.ps1`` on $stamp from the Microsoft 365")
[void]$md.AppendLine("> IP/URL web service (endpoints.office.com, ServiceArea=MEM, instance $Instance).")
[void]$md.AppendLine("> Microsoft feed version: **$ver**. Re-run monthly and re-commit.")
[void]$md.AppendLine('')
[void]$md.AppendLine("**Ports:** TCP $($tcp -join ', ') · UDP $($udp -join ', ') (123 = NTP time sync).")
[void]$md.AppendLine('')
[void]$md.AppendLine("**Enforcement:** egress is filtered at the OpenWrt router (see ``docs/network-zones.md``).")
[void]$md.AppendLine("The ``management`` zone (AsharPC) must reach these for Entra join, MDM enrollment,")
[void]$md.AppendLine("compliance check-in, app/policy delivery, and device attestation. Apply the CIDR")
[void]$md.AppendLine("lists as an allow set; FQDNs are listed for proxy/DNS-based allow-listing.")
[void]$md.AppendLine('')
[void]$md.AppendLine("## Required URLs ($($reqUrls.Count))")
[void]$md.AppendLine('')
foreach ($u in $reqUrls) { [void]$md.AppendLine("- ``$u``") }
[void]$md.AppendLine('')
[void]$md.AppendLine("## Optional / dependency URLs ($($optOnly.Count))")
[void]$md.AppendLine('')
[void]$md.AppendLine('These support dependent services (Office, auth CDNs, telemetry). Allow if the')
[void]$md.AppendLine('device uses them; not strictly required for core MDM enrollment.')
[void]$md.AppendLine('')
foreach ($u in $optOnly) { [void]$md.AppendLine("- ``$u``") }
[void]$md.AppendLine('')
[void]$md.AppendLine("## IPv4 ranges ($($ipv4.Count))")
[void]$md.AppendLine('')
[void]$md.AppendLine('See `intune-allowlist-ipv4.txt` (flat list for a router ipset/nftables set).')
[void]$md.AppendLine('')
[void]$md.AppendLine("## IPv6 ranges ($($ipv6.Count))")
[void]$md.AppendLine('')
[void]$md.AppendLine('See `intune-allowlist-ipv6.txt`.')
$md.ToString() | Set-Content "$OutputDir/intune-network-endpoints.md" -Encoding utf8

Write-Host "Wrote:" -ForegroundColor Green
Write-Host "  intune-network-endpoints.md  ($($reqUrls.Count) required + $($optOnly.Count) optional URLs)"
Write-Host "  intune-allowlist-ipv4.txt    ($($ipv4.Count) CIDRs)"
Write-Host "  intune-allowlist-ipv6.txt    ($($ipv6.Count) CIDRs)"
Write-Host "  Microsoft feed version: $ver" -ForegroundColor Cyan
